### ISSUE TITLE
Demo 1 wrong link for Contoso Sales Assistant Example

### ISSUE THREAD

**Issue by carlotta94c** [microsoft/aitour-azure-openai-assistants#9]
The link to the Contoso Sales Assistant demo 1 documentation (the option developed with Chainlit) added into [demo readme file](https://github.com/microsoft/aitour-azure-openai-assistants/blob/main/session-delivery-resources/demo-1/README.md) is broken.  Correct link is https://github.com/microsoft/aitour-azure-openai-assistants

**Comment by blackgrey0010** [comment]
any update on this issue @gloveboxes @softchris ?

cc @mbaiza27

**Comment by carlotta94c** [comment]
@blackgrey0010 addressed in my last PR https://github.com/microsoft/aitour-azure-openai-assistants/pull/11

**Comment by carlotta94c** [comment]
PR merged https://github.com/microsoft/aitour-azure-openai-assistants/pull/11, closing issue
